/* ─────────────────────────────────────────────────────────────
 * Módulo de Cotizaciones & APU – Tabulador Salarial OCENSA
 * Instructivo AEX-INS-006 • Versión 26
 *
 * Tablas Oficiales:
 * 1. Actividades Propias 2026 – 2027 (Vigencia: Julio 1, 2026 – Junio 30, 2027)
 * 2. Actividades No Propias 2026 (Vigencia: Enero 1, 2026 – Diciembre 31, 2026)
 * ───────────────────────────────────────────────────────────── */

export type OcensaActivityType = "propias" | "no_propias";

export type OcensaSpecialty =
  | "electrico"
  | "instrumentacion"
  | "maritimo"
  | "mecanica"
  | "metalmecanica"
  | "soldadura"
  | "pintura_sandblasting"
  | "obra_civil"
  | "maquinaria_equipos"
  | "hse_ambiental_calidad"
  | "servicios_apoyo";

export type OcensaLaborPosition = {
  id: string;
  code: string;
  name: string;
  activityType: OcensaActivityType;
  specialty: OcensaSpecialty;
  specialtyLabel: string;
  level: 1 | 2 | 3 | 4 | 5 | 6;
  dailyBasicSalary: number;     // Salario Básico Diario COP
  transportAllowance: number;   // Auxilio de Transporte Diario COP
  foodAllowance: number;        // Auxilio de Alimentación Diario COP
  nonSalaryAllowance?: number;  // Auxilio sin Incidencia Salarial Diario COP (en Propias)
  totalDailyRate: number;       // Total Día COP de referencia
  period: string;               // Vigencia oficial
  summary: string;              // Resumen operativo de funciones y responsabilidades
};

/* ── Escala Salarial Base Actividades Propias (Jul 2026 - Jun 2027) ── */
export const ocensaPropiasScale = {
  level1: { basic: 114854, food: 34812, transport: 8303, nonSalary: 33418, total: 191387 },
  level2: { basic: 132707, food: 34812, transport: 8303, nonSalary: 43707, total: 219528 },
  level3: { basic: 139630, food: 34812, transport: 8303, nonSalary: 48244, total: 230989 },
  level4: { basic: 164879, food: 34812, transport: 8303, nonSalary: 61746, total: 269739 },
  level5: { basic: 184864, food: 34812, transport: 8303, nonSalary: 66282, total: 294260 },
  level6: { basic: 203065, food: 34812, transport: 8303, nonSalary: 81663, total: 327843 },
} as const;

/* ── Escala Salarial Base Actividades No Propias (Ene 2026 - Dic 2026) ── */
export const ocensaNoPropiasScale = {
  level1: { basic: 60581, transport: 8303, food: 25658, total: 94542 },
  level2: { basic: 64750, transport: 8303, food: 25658, total: 98711 },
  level3: { basic: 77100, transport: 8303, food: 25658, total: 111061 },
  level4: { basic: 79924, transport: 8303, food: 25658, total: 113885 },
  level5: { basic: 112890, transport: 8303, food: 25658, total: 146851 },
} as const;

/* ══════════════════════════════════════════════════════════════════
 * CATÁLOGO COMPLETO DE PUESTOS Y FUNCIONES OCENSA
 * ══════════════════════════════════════════════════════════════════ */

export const ocensaLaborPositions: OcensaLaborPosition[] = [
  /* ─────────────────────────────────────────────────────────────
   * 1. ACTIVIDADES PROPIAS — ELÉCTRICO
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-elec-l1-op-planta",
    code: "PROP-ELEC-N1",
    name: "Operador Planta Eléctrica",
    activityType: "propias",
    specialty: "electrico",
    specialtyLabel: "Eléctrico",
    level: 1,
    dailyBasicSalary: ocensaPropiasScale.level1.basic,
    transportAllowance: ocensaPropiasScale.level1.transport,
    foodAllowance: ocensaPropiasScale.level1.food,
    nonSalaryAllowance: ocensaPropiasScale.level1.nonSalary,
    totalDailyRate: ocensaPropiasScale.level1.total,
    period: "2026 - 2027",
    summary: "Responsable de la puesta en marcha, control de parámetros (voltaje, frecuencia, horómetro), monitoreo de niveles de aceite/refrigerante y abastecimiento seguro de combustible en generadores eléctricos de obra y campamento.",
  },
  {
    id: "prop-elec-l2-ayudante",
    code: "PROP-ELEC-N2",
    name: "Ayudante Electricista",
    activityType: "propias",
    specialty: "electrico",
    specialtyLabel: "Eléctrico",
    level: 2,
    dailyBasicSalary: ocensaPropiasScale.level2.basic,
    transportAllowance: ocensaPropiasScale.level2.transport,
    foodAllowance: ocensaPropiasScale.level2.food,
    nonSalaryAllowance: ocensaPropiasScale.level2.nonSalary,
    totalDailyRate: ocensaPropiasScale.level2.total,
    period: "2026 - 2027",
    summary: "Asiste al oficial electricista en tendido y halado de conductores, armado y fijación de bandejas portacables, doblado de ductos conduit galvanizados y preparación de herramientas e instrumentos de medición.",
  },
  {
    id: "prop-elec-l4-electricista-1",
    code: "PROP-ELEC-N4",
    name: "Electricista 1",
    activityType: "propias",
    specialty: "electrico",
    specialtyLabel: "Eléctrico",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Ejecución de instalaciones eléctricas industriales en baja tensión: alambrado y ponchado de tableros de fuerza e iluminación, tendido de mallas de puesta a tierra, pruebas de continuidad y resistencia de aislamiento (Megger).",
  },
  {
    id: "prop-elec-l5-electricista-1a",
    code: "PROP-ELEC-N5",
    name: "Electricista 1A",
    activityType: "propias",
    specialty: "electrico",
    specialtyLabel: "Eléctrico",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Mantenimiento y montaje eléctrico de alta complejidad en media tensión: conexionado y comisionamiento de subestaciones, celdas de seccionamiento, variadores de frecuencia (VFD) y motores eléctricos principales en estaciones de bombeo.",
  },

  /* ─────────────────────────────────────────────────────────────
   * 2. ACTIVIDADES PROPIAS — INSTRUMENTACIÓN
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-inst-l2-ayudante",
    code: "PROP-INST-N2",
    name: "Ayudante Instrumentación",
    activityType: "propias",
    specialty: "instrumentacion",
    specialtyLabel: "Instrumentación",
    level: 2,
    dailyBasicSalary: ocensaPropiasScale.level2.basic,
    transportAllowance: ocensaPropiasScale.level2.transport,
    foodAllowance: ocensaPropiasScale.level2.food,
    nonSalaryAllowance: ocensaPropiasScale.level2.nonSalary,
    totalDailyRate: ocensaPropiasScale.level2.total,
    period: "2026 - 2027",
    summary: "Apoya en la fabricación y montaje de soportería para instrumentos de campo, tendido de cables apantallados de señal, manipulación de tubing de acero inoxidable y transporte de calibradores de proceso.",
  },
  {
    id: "prop-inst-l4-instrumentista-1",
    code: "PROP-INST-N4",
    name: "Instrumentista 1",
    activityType: "propias",
    specialty: "instrumentacion",
    specialtyLabel: "Instrumentación",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Instalación, conexionado, verificación de lazos y doblado de tubería tubing para transmisores de presión, temperatura, flujo y nivel. Mantenimiento y calibración de posicionadores en válvulas neumáticas de control.",
  },
  {
    id: "prop-inst-l5-instrumentista-1a",
    code: "PROP-INST-N5",
    name: "Instrumentista 1A",
    activityType: "propias",
    specialty: "instrumentacion",
    specialtyLabel: "Instrumentación",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Comisionamiento de lazos de control críticos bajo protocolo HART y Fieldbus; programación y calibración de sistemas de detección de fuego y gas (F&G), transmisores multiparamétricos y sistemas de paro de emergencia (ESD).",
  },

  /* ─────────────────────────────────────────────────────────────
   * 3. ACTIVIDADES PROPIAS — METALMECÁNICA & TUBERÍA
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-meta-l2-ay-pileria",
    code: "PROP-META-N2-PAIL",
    name: "Ayudante Pailería",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 2,
    dailyBasicSalary: ocensaPropiasScale.level2.basic,
    transportAllowance: ocensaPropiasScale.level2.transport,
    foodAllowance: ocensaPropiasScale.level2.food,
    nonSalaryAllowance: ocensaPropiasScale.level2.nonSalary,
    totalDailyRate: ocensaPropiasScale.level2.total,
    period: "2026 - 2027",
    summary: "Asistencia al oficial pailero en corte de láminas y perfiles con oxicorte y plasma, pulido de bordes con amoladora angular, desbaste mecánico y sujeción de piezas para apuntalamiento estructural.",
  },
  {
    id: "prop-meta-l2-ay-tuberia",
    code: "PROP-META-N2-TUB",
    name: "Ayudante Tubería",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 2,
    dailyBasicSalary: ocensaPropiasScale.level2.basic,
    transportAllowance: ocensaPropiasScale.level2.transport,
    foodAllowance: ocensaPropiasScale.level2.food,
    nonSalaryAllowance: ocensaPropiasScale.level2.nonSalary,
    totalDailyRate: ocensaPropiasScale.level2.total,
    period: "2026 - 2027",
    summary: "Apoyo en manipulación de tubos de acero al carbono, colocación de soportes temporales, limpieza de biseles con escobilla de acero, manejo de alineadores externos (clamp) y asistencia en pruebas de estanqueidad.",
  },
  {
    id: "prop-meta-l4-pailero-1",
    code: "PROP-META-N4-PAIL",
    name: "Pailero 1",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Trazo geométrico, corte, conformado y armado de estructuras de acero, chimeneas industriales, ductos de ventilación, tolvas, plataformas y recipientes metálicos según planos de ingeniería mecánica.",
  },
  {
    id: "prop-meta-l4-tubero-1",
    code: "PROP-META-N4-TUB",
    name: "Tubero 1",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Interpretación de planos isométricos P&ID; corte, biselado milimétrico y presentación de tuberías de proceso y bridas en líneas de acero al carbono e inoxidable, asegurando alineación de juntas.",
  },
  {
    id: "prop-meta-l4-montador-1",
    code: "PROP-META-N4-MONT",
    name: "Montador 1",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Montaje, posicionamiento e izaje de piezas estructurales metálicas, pasarelas de inspección, escaleras de tanques y soportes de tubería en estaciones y líneas de transporte.",
  },
  {
    id: "prop-meta-l5-pailero-1a",
    code: "PROP-META-N5-PAIL",
    name: "Pailero 1A",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Pailería de alta precisión bajo código ASME para recipientes a presión, intercambiadores de calor, techos flotantes y mantos de tanques de almacenamiento de hidrocarburos de gran capacidad.",
  },
  {
    id: "prop-meta-l5-tubero-1a",
    code: "PROP-META-N5-TUB",
    name: "Tubero 1A",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Fabricación y montaje de líneas críticas de oleoducto de alta presión (clase ANSI 600 a 1500), cruces subfluviales, trampas de raspadores (scrapers) y acometidas principales con tolerancias cero.",
  },
  {
    id: "prop-meta-l5-montador-1a",
    code: "PROP-META-N5-MONT",
    name: "Montador 1A",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Líder de montaje mecánico para izajes en tándem de equipos pesados (chimeneas completas, bombas multietapas, módulos skid) con control topográfico de verticalidad y torqueado estructural.",
  },
  {
    id: "prop-meta-l5-alineador",
    code: "PROP-META-N5-ALIN",
    name: "Alineador de Tuberías",
    activityType: "propias",
    specialty: "metalmecanica",
    specialtyLabel: "Metalmecánica",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Especialista en el enfrentamiento de juntas de tubería de línea de oleoducto mediante grapas internas neumáticas e hidráulicas, garantizando la separación de raíz (gap) requerida para la soldadura continua.",
  },

  /* ─────────────────────────────────────────────────────────────
   * 4. ACTIVIDADES PROPIAS — SOLDADURA
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-sold-l2-ayudante",
    code: "PROP-SOLD-N2",
    name: "Ayudante Soldadura",
    activityType: "propias",
    specialty: "soldadura",
    specialtyLabel: "Soldadura",
    level: 2,
    dailyBasicSalary: ocensaPropiasScale.level2.basic,
    transportAllowance: ocensaPropiasScale.level2.transport,
    foodAllowance: ocensaPropiasScale.level2.food,
    nonSalaryAllowance: ocensaPropiasScale.level2.nonSalary,
    totalDailyRate: ocensaPropiasScale.level2.total,
    period: "2026 - 2027",
    summary: "Control y conservación térmica de electrodos en termos portátiles, precalentamiento con antorcha de oxigas, limpieza entre pases con cepillo de alambre y protección de viento y lluvia para el área de soldadura.",
  },
  {
    id: "prop-sold-l3-esmerilador",
    code: "PROP-SOLD-N3",
    name: "Esmerilador",
    activityType: "propias",
    specialty: "soldadura",
    specialtyLabel: "Soldadura",
    level: 3,
    dailyBasicSalary: ocensaPropiasScale.level3.basic,
    transportAllowance: ocensaPropiasScale.level3.transport,
    foodAllowance: ocensaPropiasScale.level3.food,
    nonSalaryAllowance: ocensaPropiasScale.level3.nonSalary,
    totalDailyRate: ocensaPropiasScale.level3.total,
    period: "2026 - 2027",
    summary: "Desbaste mecánico del pase de raíz, limpieza profunda entre cordones de soldadura, biselado de tubería y remoción de discontinuidades metalúrgicas detectadas por ultrasonido o radiografía industrial.",
  },
  {
    id: "prop-sold-l4-soldador-1",
    code: "PROP-SOLD-N4",
    name: "Soldador 1",
    activityType: "propias",
    specialty: "soldadura",
    specialtyLabel: "Soldadura",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Soldador calificado en proceso SMAW (electrodo revestido) en posiciones 3G y 4G para estructuras de soporte, pasarelas metálicas, placas base y tuberías de baja y media presión sin ensayos no destructivos severos.",
  },
  {
    id: "prop-sold-l5-soldador-1a",
    code: "PROP-SOLD-N5",
    name: "Soldador 1A (Línea API 1104 / ASME IX)",
    activityType: "propias",
    specialty: "soldadura",
    specialtyLabel: "Soldadura",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Soldador calificado en posición 6G fija para líneas principales de oleoducto bajo norma API 1104 / ASME IX: aplicación de pase de raíz con electrodo celulósico, relleno y presentación con 100% de aprobación radiográfica.",
  },
  {
    id: "prop-sold-l5-soldador-argonero",
    code: "PROP-SOLD-N5-ARG",
    name: "Soldador Argonero (TIG / GTAW)",
    activityType: "propias",
    specialty: "soldadura",
    specialtyLabel: "Soldadura",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Especialista en soldadura de alta pureza con gas argón (proceso GTAW/TIG) para pase de raíz en tubería de acero inoxidable, aleaciones de cromo-molibdeno y líneas de instrumentación de alta presión.",
  },

  /* ─────────────────────────────────────────────────────────────
   * 5. ACTIVIDADES PROPIAS — MECÁNICA INDUSTRIAL
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-meca-l4-mecanico-1",
    code: "PROP-MECA-N4",
    name: "Mecánico 1",
    activityType: "propias",
    specialty: "mecanica",
    specialtyLabel: "Mecánica",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Mantenimiento preventivo y correctivo de bombas centrífugas de inyección, compresores reciprocantes de aire, válvulas motorizadas, cambio de empaquetaduras y rodamientos industriales en estaciones.",
  },
  {
    id: "prop-meca-l5-mecanico-1a",
    code: "PROP-MECA-N5",
    name: "Mecánico 1A",
    activityType: "propias",
    specialty: "mecanica",
    specialtyLabel: "Mecánica",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Alineación láser de precisión en trenes motobomba de transporte de crudo; revisión y reemplazo de sellos mecánicos tipo cartucho, análisis de holguras internas de bombas multietapas y diagnóstico por vibraciones.",
  },

  /* ─────────────────────────────────────────────────────────────
   * 6. ACTIVIDADES PROPIAS — PINTURA, SANDBLASTING & HSE
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-pint-l2-ayudante",
    code: "PROP-PINT-N2",
    name: "Ayudante de Pintura",
    activityType: "propias",
    specialty: "pintura_sandblasting",
    specialtyLabel: "Pintura y Abrasivos",
    level: 2,
    dailyBasicSalary: ocensaPropiasScale.level2.basic,
    transportAllowance: ocensaPropiasScale.level2.transport,
    foodAllowance: ocensaPropiasScale.level2.food,
    nonSalaryAllowance: ocensaPropiasScale.level2.nonSalary,
    totalDailyRate: ocensaPropiasScale.level2.total,
    period: "2026 - 2027",
    summary: "Limpieza manual y mecánica de superficies con solvente y lija, enmascaramiento de equipos e instrumentos, mezcla preliminar de componentes epóxicos y limpieza de mangueras y boquillas de aplicación.",
  },
  {
    id: "prop-pint-l3-sandblastero",
    code: "PROP-PINT-N3-SAND",
    name: "Sandblastero",
    activityType: "propias",
    specialty: "pintura_sandblasting",
    specialtyLabel: "Pintura y Abrasivos",
    level: 3,
    dailyBasicSalary: ocensaPropiasScale.level3.basic,
    transportAllowance: ocensaPropiasScale.level3.transport,
    foodAllowance: ocensaPropiasScale.level3.food,
    nonSalaryAllowance: ocensaPropiasScale.level3.nonSalary,
    totalDailyRate: ocensaPropiasScale.level3.total,
    period: "2026 - 2027",
    summary: "Operación de tolvas de chorro abrasivo y mangueras de alta presión para limpieza superficial de tuberías y tanques según normas SSPC-SP10 (Metal casi blanco) y SSPC-SP5 (Metal blanco).",
  },
  {
    id: "prop-pint-l3-pintor",
    code: "PROP-PINT-N3-PINT",
    name: "Pintor",
    activityType: "propias",
    specialty: "pintura_sandblasting",
    specialtyLabel: "Pintura y Abrasivos",
    level: 3,
    dailyBasicSalary: ocensaPropiasScale.level3.basic,
    transportAllowance: ocensaPropiasScale.level3.transport,
    foodAllowance: ocensaPropiasScale.level3.food,
    nonSalaryAllowance: ocensaPropiasScale.level3.nonSalary,
    totalDailyRate: ocensaPropiasScale.level3.total,
    period: "2026 - 2027",
    summary: "Aplicación de esquemas de pintura industrial de alto rendimiento (imprimantes ricos en zinc, epóxicos de altos sólidos y acabados en poliuretano) mediante equipos airless para protección anticorrosiva.",
  },
  {
    id: "prop-pint-l3-sandblastero-pintor",
    code: "PROP-PINT-N3-DUAL",
    name: "Sandblastero Pintor",
    activityType: "propias",
    specialty: "pintura_sandblasting",
    specialtyLabel: "Pintura y Abrasivos",
    level: 3,
    dailyBasicSalary: ocensaPropiasScale.level3.basic,
    transportAllowance: ocensaPropiasScale.level3.transport,
    foodAllowance: ocensaPropiasScale.level3.food,
    nonSalaryAllowance: ocensaPropiasScale.level3.nonSalary,
    totalDailyRate: ocensaPropiasScale.level3.total,
    period: "2026 - 2027",
    summary: "Técnico integral capacitado para realizar tanto la limpieza con chorro de arena/granalla como la aplicación inmediata de los recubrimientos protectores antes de que ocurra oxidación rápida (flash rust).",
  },
  {
    id: "prop-hse-l3-vigia",
    code: "PROP-HSE-N3",
    name: "Vigía HSE",
    activityType: "propias",
    specialty: "hse_ambiental_calidad",
    specialtyLabel: "HSE y Calidad",
    level: 3,
    dailyBasicSalary: ocensaPropiasScale.level3.basic,
    transportAllowance: ocensaPropiasScale.level3.transport,
    foodAllowance: ocensaPropiasScale.level3.food,
    nonSalaryAllowance: ocensaPropiasScale.level3.nonSalary,
    totalDailyRate: ocensaPropiasScale.level3.total,
    period: "2026 - 2027",
    summary: "Monitoreo continuo de seguridad en campo: verificación de permisos de trabajo (PTW), análisis de trabajo seguro (ATS), delimitación de zonas calientes, uso de EPP y vigía contra incendios durante soldadura.",
  },
  {
    id: "prop-hse-l5-rescatista",
    code: "PROP-HSE-N5",
    name: "Rescatista de Alturas",
    activityType: "propias",
    specialty: "hse_ambiental_calidad",
    specialtyLabel: "HSE y Calidad",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Personal certificado y entrenado en rescate vertical y rescate en espacios confinados; supervisión de líneas de vida, arneses, puntos de anclaje certificados y activación de planes de evacuación médica de emergencia.",
  },
  {
    id: "prop-hse-l6-inspector",
    code: "PROP-HSE-N6",
    name: "Inspector HSE / Ambiental",
    activityType: "propias",
    specialty: "hse_ambiental_calidad",
    specialtyLabel: "HSE y Calidad",
    level: 6,
    dailyBasicSalary: ocensaPropiasScale.level6.basic,
    transportAllowance: ocensaPropiasScale.level6.transport,
    foodAllowance: ocensaPropiasScale.level6.food,
    nonSalaryAllowance: ocensaPropiasScale.level6.nonSalary,
    totalDailyRate: ocensaPropiasScale.level6.total,
    period: "2026 - 2027",
    summary: "Profesional líder de Seguridad, Salud en el Trabajo y Medio Ambiente: elaboración de matrices de riesgo, auditorías operativas, investigación de incidentes, control de vertimientos y manejo de residuos peligrosos (RESPEL).",
  },

  /* ─────────────────────────────────────────────────────────────
   * 7. ACTIVIDADES PROPIAS — MAQUINARIA PESADA, IZAJES Y OBRAS CIVILES
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-maqu-l3-op-grua-40t",
    code: "PROP-MAQU-N3-G40",
    name: "Operador Grúa hasta 40 Ton",
    activityType: "propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 3,
    dailyBasicSalary: ocensaPropiasScale.level3.basic,
    transportAllowance: ocensaPropiasScale.level3.transport,
    foodAllowance: ocensaPropiasScale.level3.food,
    nonSalaryAllowance: ocensaPropiasScale.level3.nonSalary,
    totalDailyRate: ocensaPropiasScale.level3.total,
    period: "2026 - 2027",
    summary: "Operación de grúas móviles telescópicas con capacidad de carga de hasta 40 toneladas para cargue y descargue de tubos, perfiles y contenedores, aplicando tablas de carga y estabilidad.",
  },
  {
    id: "prop-maqu-l3-aparejador",
    code: "PROP-MAQU-N3-APAR",
    name: "Aparejador / Rigger",
    activityType: "propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 3,
    dailyBasicSalary: ocensaPropiasScale.level3.basic,
    transportAllowance: ocensaPropiasScale.level3.transport,
    foodAllowance: ocensaPropiasScale.level3.food,
    nonSalaryAllowance: ocensaPropiasScale.level3.nonSalary,
    totalDailyRate: ocensaPropiasScale.level3.total,
    period: "2026 - 2027",
    summary: "Inspección previa y descarte de elementos de izaje (eslingas sintéticas, grilletes forjados, estrobos de cable de acero); amarre seguro de cargas y dirección del operador mediante señales universales.",
  },
  {
    id: "prop-maqu-l4-op-grua-90t",
    code: "PROP-MAQU-N4-G90",
    name: "Operador Grúa hasta 90 Ton",
    activityType: "propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Operación de grúa de alto tonelaje para izajes críticos: posicionamiento de secciones de chimeneas, bombas de gran potencia, módulos skid y tuberías de gran diámetro en estaciones.",
  },
  {
    id: "prop-maqu-l4-sideboom",
    code: "PROP-MAQU-N4-SIDE",
    name: "Operador Sideboom (Tiendetubos)",
    activityType: "propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Operación especializada de tractor tiendetubos (Sideboom) para bajada coordinada de tubería a la zanja del oleoducto en desfiles de línea regular y cruces especiales.",
  },
  {
    id: "prop-maqu-l4-retro-manlift",
    code: "PROP-MAQU-N4-RETRO",
    name: "Operador Retroexcavadora / Manlift / Bobcat",
    activityType: "propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Manejo de retroexcavadora sobre orugas para apertura y tapado de zanjas, minicargador Bobcat para movimientos de tierra en espacios reducidos y plataformas elevadoras (Manlift) para trabajos en altura.",
  },
  {
    id: "prop-maqu-l4-torque",
    code: "PROP-MAQU-N4-TORQ",
    name: "Operador Herramientas de Torque Hidráulico",
    activityType: "propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Apriete y desapriete calibrado de espárragos en uniones bridadas de alta presión de oleoducto usando llaves hidráulicas Hytorc y multiplicadores, garantizando sellado hermético sin fugas.",
  },
  {
    id: "prop-maqu-l4-pruebas-hidro",
    code: "PROP-MAQU-N4-HIDRO",
    name: "Operador Equipo Pruebas Hidrostáticas",
    activityType: "propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Llenado, limpieza con raspadores, presurización escalonada con bombas de inyección, registro termográfico y monitoreo con balanza de pesos muertos para certificar la integridad mecánica de tuberías.",
  },
  {
    id: "prop-maqu-l4-andamiro-1",
    code: "PROP-CIV-N4-ANDAM",
    name: "Andamiero 1",
    activityType: "propias",
    specialty: "obra_civil",
    specialtyLabel: "Obras Civiles y Estructuras",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Armado, arriostramiento, nivelación y desmonte de andamios modulares certificados tipo Layher para trabajos en altura en chimeneas, cubiertas de tanques y pasarelas de estaciones.",
  },
  {
    id: "prop-maqu-l5-andamiro-1a",
    code: "PROP-CIV-N5-ANDAM",
    name: "Andamiero 1A",
    activityType: "propias",
    specialty: "obra_civil",
    specialtyLabel: "Obras Civiles y Estructuras",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Diseñador y jefe de cuadrilla de andamiaje especializado: montaje de andamios colgantes en ríos, voladizos complejos sobre chimeneas y cálculo de cargas dinámicas con tarjeta verde de certificación.",
  },
  {
    id: "prop-civ-l6-capataz",
    code: "PROP-CIV-N6-CAP",
    name: "Capataz General de Obra",
    activityType: "propias",
    specialty: "obra_civil",
    specialtyLabel: "Obras Civiles y Estructuras",
    level: 6,
    dailyBasicSalary: ocensaPropiasScale.level6.basic,
    transportAllowance: ocensaPropiasScale.level6.transport,
    foodAllowance: ocensaPropiasScale.level6.food,
    nonSalaryAllowance: ocensaPropiasScale.level6.nonSalary,
    totalDailyRate: ocensaPropiasScale.level6.total,
    period: "2026 - 2027",
    summary: "Líder de campo responsable de coordinar cuadrillas de obra civil, mecánica, soldadura y pintura; distribución de frentes de trabajo, control de rendimiento diario y enlace directo con la dirección de obra.",
  },
  {
    id: "prop-civ-l6-topografo",
    code: "PROP-CIV-N6-TOPO",
    name: "Topógrafo QA/QC, Calidad y Cantidad",
    activityType: "propias",
    specialty: "obra_civil",
    specialtyLabel: "Obras Civiles y Estructuras",
    level: 6,
    dailyBasicSalary: ocensaPropiasScale.level6.basic,
    transportAllowance: ocensaPropiasScale.level6.transport,
    foodAllowance: ocensaPropiasScale.level6.food,
    nonSalaryAllowance: ocensaPropiasScale.level6.nonSalary,
    totalDailyRate: ocensaPropiasScale.level6.total,
    period: "2026 - 2027",
    summary: "Levantamiento de alta precisión con estación total y GPS diferencial georreferenciado; control de pendientes de zanja, cálculo volumétrico de excavaciones y elaboración de planos As-Built de línea.",
  },

  /* ─────────────────────────────────────────────────────────────
   * 8. ACTIVIDADES PROPIAS — SERVICIOS GENERALES Y OPERATIVOS
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-serv-l1-obrero",
    code: "PROP-SERV-N1-OBR",
    name: "Obrero / Ayudante General",
    activityType: "propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios de Apoyo",
    level: 1,
    dailyBasicSalary: ocensaPropiasScale.level1.basic,
    transportAllowance: ocensaPropiasScale.level1.transport,
    foodAllowance: ocensaPropiasScale.level1.food,
    nonSalaryAllowance: ocensaPropiasScale.level1.nonSalary,
    totalDailyRate: ocensaPropiasScale.level1.total,
    period: "2026 - 2027",
    summary: "Excavación manual, acopio y acarreo de materiales, limpieza de áreas de trabajo, mezcla de concreto en sitio y labores generales de apoyo a cuadrillas técnicas en frentes de trabajo.",
  },
  {
    id: "prop-serv-l1-conductor",
    code: "PROP-SERV-N1-COND",
    name: "Conductor Vehículo Liviano / Pasajeros",
    activityType: "propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios de Apoyo",
    level: 1,
    dailyBasicSalary: ocensaPropiasScale.level1.basic,
    transportAllowance: ocensaPropiasScale.level1.transport,
    foodAllowance: ocensaPropiasScale.level1.food,
    nonSalaryAllowance: ocensaPropiasScale.level1.nonSalary,
    totalDailyRate: ocensaPropiasScale.level1.total,
    period: "2026 - 2027",
    summary: "Transporte seguro de personal técnico, ingenieros y cuadrillas en camionetas 4x4 y camionetas cerradas entre campamentos, bases operativas y frentes de obra en el Bajo Cauca.",
  },
  {
    id: "prop-serv-l1-paletero",
    code: "PROP-SERV-N1-TRAF",
    name: "Controlador de Tráfico / Paletero",
    activityType: "propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios de Apoyo",
    level: 1,
    dailyBasicSalary: ocensaPropiasScale.level1.basic,
    transportAllowance: ocensaPropiasScale.level1.transport,
    foodAllowance: ocensaPropiasScale.level1.food,
    nonSalaryAllowance: ocensaPropiasScale.level1.nonSalary,
    totalDailyRate: ocensaPropiasScale.level1.total,
    period: "2026 - 2027",
    summary: "Regulación del tráfico vehicular en accesos viales, desvíos temporales e ingresos de maquinaria pesada a frentes de obra con señalización reglamentaria y radio de comunicaciones.",
  },
  {
    id: "prop-serv-l2-bodeguero",
    code: "PROP-SERV-N2-BOD",
    name: "Ayudante de Bodega o Bodeguero",
    activityType: "propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios de Apoyo",
    level: 2,
    dailyBasicSalary: ocensaPropiasScale.level2.basic,
    transportAllowance: ocensaPropiasScale.level2.transport,
    foodAllowance: ocensaPropiasScale.level2.food,
    nonSalaryAllowance: ocensaPropiasScale.level2.nonSalary,
    totalDailyRate: ocensaPropiasScale.level2.total,
    period: "2026 - 2027",
    summary: "Recepción de materiales, almacenamiento ordenado en estanterías, entrega contra vales de salida de obra, custodia de herramientas menores y control de existencias físicas en almacén.",
  },
  {
    id: "prop-serv-l4-almacenista",
    code: "PROP-SERV-N4-ALM",
    name: "Almacenista Principal",
    activityType: "propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios de Apoyo",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Gestión y administración integral de inventarios: control de Kardex, cotejo de remisiones contra órdenes de compra, control de consumibles críticos y emisión de alertas de stock mínimo.",
  },

  /* ─────────────────────────────────────────────────────────────
   * 9. ACTIVIDADES PROPIAS — ESPECIALIDAD MARÍTIMA
   * ───────────────────────────────────────────────────────────── */
  {
    id: "prop-mar-l1-marinero-cubierta",
    code: "PROP-MAR-N1",
    name: "Marinero Costanero de Cubierta",
    activityType: "propias",
    specialty: "maritimo",
    specialtyLabel: "Operaciones Marítimas",
    level: 1,
    dailyBasicSalary: ocensaPropiasScale.level1.basic,
    transportAllowance: ocensaPropiasScale.level1.transport,
    foodAllowance: ocensaPropiasScale.level1.food,
    nonSalaryAllowance: ocensaPropiasScale.level1.nonSalary,
    totalDailyRate: ocensaPropiasScale.level1.total,
    period: "2026 - 2027",
    summary: "Maniobras de amarre, desatraque, limpieza de cubierta y mantenimiento básico en embarcaciones de apoyo y lanchas de transporte fluvial/marítimo del terminal.",
  },
  {
    id: "prop-mar-l2-conector-offshore",
    code: "PROP-MAR-N2",
    name: "Conector Off Shore / Marinero de Cubierta",
    activityType: "propias",
    specialty: "maritimo",
    specialtyLabel: "Operaciones Marítimas",
    level: 2,
    dailyBasicSalary: ocensaPropiasScale.level2.basic,
    transportAllowance: ocensaPropiasScale.level2.transport,
    foodAllowance: ocensaPropiasScale.level2.food,
    nonSalaryAllowance: ocensaPropiasScale.level2.nonSalary,
    totalDailyRate: ocensaPropiasScale.level2.total,
    period: "2026 - 2027",
    summary: "Conexión de mangueras submarinas y flotantes en monoboya (SPM) para cargue de tanqueros de exportación de crudo y operaciones de acople marítimo.",
  },
  {
    id: "prop-mar-l3-buzo-segunda",
    code: "PROP-MAR-N3",
    name: "Buzo Segunda / Marinero Timonel",
    activityType: "propias",
    specialty: "maritimo",
    specialtyLabel: "Operaciones Marítimas",
    level: 3,
    dailyBasicSalary: ocensaPropiasScale.level3.basic,
    transportAllowance: ocensaPropiasScale.level3.transport,
    foodAllowance: ocensaPropiasScale.level3.food,
    nonSalaryAllowance: ocensaPropiasScale.level3.nonSalary,
    totalDailyRate: ocensaPropiasScale.level3.total,
    period: "2026 - 2027",
    summary: "Inspección subacuática visual y por ultrasonido de mangueras submarinas, cadenas de anclaje, ánodos de sacrificio del oleoducto marino y maniobras de buceo profesional.",
  },
  {
    id: "prop-mar-l4-oficial-puente-2800",
    code: "PROP-MAR-N4",
    name: "Oficial Puente Regional hasta 2800 TRB",
    activityType: "propias",
    specialty: "maritimo",
    specialtyLabel: "Operaciones Marítimas",
    level: 4,
    dailyBasicSalary: ocensaPropiasScale.level4.basic,
    transportAllowance: ocensaPropiasScale.level4.transport,
    foodAllowance: ocensaPropiasScale.level4.food,
    nonSalaryAllowance: ocensaPropiasScale.level4.nonSalary,
    totalDailyRate: ocensaPropiasScale.level4.total,
    period: "2026 - 2027",
    summary: "Navegación y gobierno de remolcadores de apoyo y barcazas de servicio costa afuera hasta 2800 toneladas de registro bruto en el área del terminal marítimo.",
  },
  {
    id: "prop-mar-l5-contramaestre",
    code: "PROP-MAR-N5",
    name: "Contramaestre AB / Oficial de Máquinas 3000 kW",
    activityType: "propias",
    specialty: "maritimo",
    specialtyLabel: "Operaciones Marítimas",
    level: 5,
    dailyBasicSalary: ocensaPropiasScale.level5.basic,
    transportAllowance: ocensaPropiasScale.level5.transport,
    foodAllowance: ocensaPropiasScale.level5.food,
    nonSalaryAllowance: ocensaPropiasScale.level5.nonSalary,
    totalDailyRate: ocensaPropiasScale.level5.total,
    period: "2026 - 2027",
    summary: "Jefatura de cubierta marina y supervisión del cuarto de máquinas de remolcadores principales de alta potencia (hasta 3000 kW) en maniobras de atraque de buques petroleros.",
  },
  {
    id: "prop-mar-l6-oficial-puente",
    code: "PROP-MAR-N6",
    name: "Oficial de Puente / Capitán de Maniobra",
    activityType: "propias",
    specialty: "maritimo",
    specialtyLabel: "Operaciones Marítimas",
    level: 6,
    dailyBasicSalary: ocensaPropiasScale.level6.basic,
    transportAllowance: ocensaPropiasScale.level6.transport,
    foodAllowance: ocensaPropiasScale.level6.food,
    nonSalaryAllowance: ocensaPropiasScale.level6.nonSalary,
    totalDailyRate: ocensaPropiasScale.level6.total,
    period: "2026 - 2027",
    summary: "Oficial superior a cargo de la navegación, seguridad marítima y pilotaje en el atraque y cargue seguro de supertanqueros en las monoboyas del terminal costa afuera.",
  },

  /* ═════════════════════════════════════════════════════════════
   * 10. ACTIVIDADES NO PROPIAS 2026 (SERVICIOS COMPLEMENTARIOS)
   * ═════════════════════════════════════════════════════════════ */
  {
    id: "noprop-l1-obrero",
    code: "NOPROP-N1-OBR",
    name: "Obrero (No Propias)",
    activityType: "no_propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios Generales",
    level: 1,
    dailyBasicSalary: ocensaNoPropiasScale.level1.basic,
    transportAllowance: ocensaNoPropiasScale.level1.transport,
    foodAllowance: ocensaNoPropiasScale.level1.food,
    totalDailyRate: ocensaNoPropiasScale.level1.total,
    period: "2026",
    summary: "Labores manuales básicas de cargue, descargue, limpieza y despeje en obras complementarias, campamentos y bodegas secundarias.",
  },
  {
    id: "noprop-l1-obrero-descontamina",
    code: "NOPROP-N1-DESCONT",
    name: "Obrero de Descontaminación",
    activityType: "no_propias",
    specialty: "hse_ambiental_calidad",
    specialtyLabel: "HSE y Calidad",
    level: 1,
    dailyBasicSalary: ocensaNoPropiasScale.level1.basic,
    transportAllowance: ocensaNoPropiasScale.level1.transport,
    foodAllowance: ocensaNoPropiasScale.level1.food,
    totalDailyRate: ocensaNoPropiasScale.level1.total,
    period: "2026",
    summary: "Recolección y limpieza manual de suelos o vegetación con barreras oleofílicas, paños absorbentes y almacenamiento en canecas para residuos contaminados.",
  },
  {
    id: "noprop-l1-jardinero",
    code: "NOPROP-N1-JARD",
    name: "Jardinero",
    activityType: "no_propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios Generales",
    level: 1,
    dailyBasicSalary: ocensaNoPropiasScale.level1.basic,
    transportAllowance: ocensaNoPropiasScale.level1.transport,
    foodAllowance: ocensaNoPropiasScale.level1.food,
    totalDailyRate: ocensaNoPropiasScale.level1.total,
    period: "2026",
    summary: "Mantenimiento paisajístico, siembra de plantas ornamentales, riego y poda manual en los alrededores de oficinas y campamentos de estación.",
  },
  {
    id: "noprop-l1-fumigador",
    code: "NOPROP-N1-FUMIG",
    name: "Obrero Apicultor y Fumigador",
    activityType: "no_propias",
    specialty: "hse_ambiental_calidad",
    specialtyLabel: "HSE y Calidad",
    level: 1,
    dailyBasicSalary: ocensaNoPropiasScale.level1.basic,
    transportAllowance: ocensaNoPropiasScale.level1.transport,
    foodAllowance: ocensaNoPropiasScale.level1.food,
    totalDailyRate: ocensaNoPropiasScale.level1.total,
    period: "2026",
    summary: "Fumigación de control de vectores y plagas en campamentos, así como rescate y reubicación controlada de enjambres de abejas y avispas en áreas de trabajo.",
  },
  {
    id: "noprop-l1-senializador",
    code: "NOPROP-N1-VIAL",
    name: "Señalizador Vial",
    activityType: "no_propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios Generales",
    level: 1,
    dailyBasicSalary: ocensaNoPropiasScale.level1.basic,
    transportAllowance: ocensaNoPropiasScale.level1.transport,
    foodAllowance: ocensaNoPropiasScale.level1.food,
    totalDailyRate: ocensaNoPropiasScale.level1.total,
    period: "2026",
    summary: "Control y orientación del tránsito vehicular en caminos vecinales y accesos secundarios a instalaciones mediante paletas pare/siga y conos.",
  },
  {
    id: "noprop-l2-obrero-exp",
    code: "NOPROP-N2-OBR-EXP",
    name: "Obrero con Experiencia",
    activityType: "no_propias",
    specialty: "obra_civil",
    specialtyLabel: "Obras Civiles y Estructuras",
    level: 2,
    dailyBasicSalary: ocensaNoPropiasScale.level2.basic,
    transportAllowance: ocensaNoPropiasScale.level2.transport,
    foodAllowance: ocensaNoPropiasScale.level2.food,
    totalDailyRate: ocensaNoPropiasScale.level2.total,
    period: "2026",
    summary: "Obrero práctico con habilidad en nivelación de terrenos, armado de formaletas de madera, excavaciones técnicas y preparación de mezclas de concreto.",
  },
  {
    id: "noprop-l2-ayudante-civil",
    code: "NOPROP-N2-AY-CIV",
    name: "Ayudante de Obra Civil",
    activityType: "no_propias",
    specialty: "obra_civil",
    specialtyLabel: "Obras Civiles y Estructuras",
    level: 2,
    dailyBasicSalary: ocensaNoPropiasScale.level2.basic,
    transportAllowance: ocensaNoPropiasScale.level2.transport,
    foodAllowance: ocensaNoPropiasScale.level2.food,
    totalDailyRate: ocensaNoPropiasScale.level2.total,
    period: "2026",
    summary: "Asistencia directa al oficial de albañilería en colocación de ladrillos, vaciado de contrapisos, fundición de dados y armado de aceros de refuerzo.",
  },
  {
    id: "noprop-l2-guadanador",
    code: "NOPROP-N2-GUAD",
    name: "Guadañador",
    activityType: "no_propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios Generales",
    level: 2,
    dailyBasicSalary: ocensaNoPropiasScale.level2.basic,
    transportAllowance: ocensaNoPropiasScale.level2.transport,
    foodAllowance: ocensaNoPropiasScale.level2.food,
    totalDailyRate: ocensaNoPropiasScale.level2.total,
    period: "2026",
    summary: "Roza y corte mecánico de maleza con guadañadora de motor en el Derecho de Vía (DDV) del oleoducto y cercas perimetrales de estaciones.",
  },
  {
    id: "noprop-l2-aparejador",
    code: "NOPROP-N2-APAR",
    name: "Aparejador de Grúa / Cargas (No Propias)",
    activityType: "no_propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 2,
    dailyBasicSalary: ocensaNoPropiasScale.level2.basic,
    transportAllowance: ocensaNoPropiasScale.level2.transport,
    foodAllowance: ocensaNoPropiasScale.level2.food,
    totalDailyRate: ocensaNoPropiasScale.level2.total,
    period: "2026",
    summary: "Estrobado y amarre de materiales menores, herramientas y repuestos para maniobras rutinarias de cargue en camiones grúa y grúas de patio.",
  },
  {
    id: "noprop-l3-vigilante",
    code: "NOPROP-N3-VIG",
    name: "Vigilante",
    activityType: "no_propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios Generales",
    level: 3,
    dailyBasicSalary: ocensaNoPropiasScale.level3.basic,
    transportAllowance: ocensaNoPropiasScale.level3.transport,
    foodAllowance: ocensaNoPropiasScale.level3.food,
    totalDailyRate: ocensaNoPropiasScale.level3.total,
    period: "2026",
    summary: "Custodia de frentes de obra, campamentos y bodegas; control de acceso de personas, revisión de carnets, registro en minuta y rondas perimetrales nocturnas.",
  },
  {
    id: "noprop-l4-albanil",
    code: "NOPROP-N4-ALB",
    name: "Albañil / Oficial de Construcción",
    activityType: "no_propias",
    specialty: "obra_civil",
    specialtyLabel: "Obras Civiles y Estructuras",
    level: 4,
    dailyBasicSalary: ocensaNoPropiasScale.level4.basic,
    transportAllowance: ocensaNoPropiasScale.level4.transport,
    foodAllowance: ocensaNoPropiasScale.level4.food,
    totalDailyRate: ocensaNoPropiasScale.level4.total,
    period: "2026",
    summary: "Construcción de mampostería, pañetes, pisos de concreto, obras de drenaje (cunetas, sumideros) y adecuaciones locativas en campamentos y estaciones.",
  },
  {
    id: "noprop-l4-op-veh-pesado",
    code: "NOPROP-N4-VOLQ",
    name: "Operador de Vehículo Pesado (Volqueta / Camión)",
    activityType: "no_propias",
    specialty: "maquinaria_equipos",
    specialtyLabel: "Maquinaria y Equipos",
    level: 4,
    dailyBasicSalary: ocensaNoPropiasScale.level4.basic,
    transportAllowance: ocensaNoPropiasScale.level4.transport,
    foodAllowance: ocensaNoPropiasScale.level4.food,
    totalDailyRate: ocensaNoPropiasScale.level4.total,
    period: "2026",
    summary: "Conducción y operación de volquetas de 7m³ y 14m³ para transporte de material de préstamo, escombros, arenas y agregados en obras civiles.",
  },
  {
    id: "noprop-l4-tecnico-electrico",
    code: "NOPROP-N4-ELEC",
    name: "Técnico Electricista (No Propias)",
    activityType: "no_propias",
    specialty: "electrico",
    specialtyLabel: "Eléctrico",
    level: 4,
    dailyBasicSalary: ocensaNoPropiasScale.level4.basic,
    transportAllowance: ocensaNoPropiasScale.level4.transport,
    foodAllowance: ocensaNoPropiasScale.level4.food,
    totalDailyRate: ocensaNoPropiasScale.level4.total,
    period: "2026",
    summary: "Instalación y mantenimiento de redes eléctricas residenciales/comerciales en campamentos, casetas de vigilancia, iluminación exterior y tomas de fuerza auxiliar.",
  },
  {
    id: "noprop-l4-capataz-roceria",
    code: "NOPROP-N4-CAP-ROC",
    name: "Capataz de Zonas Verdes y Rocería",
    activityType: "no_propias",
    specialty: "servicios_apoyo",
    specialtyLabel: "Servicios Generales",
    level: 4,
    dailyBasicSalary: ocensaNoPropiasScale.level4.basic,
    transportAllowance: ocensaNoPropiasScale.level4.transport,
    foodAllowance: ocensaNoPropiasScale.level4.food,
    totalDailyRate: ocensaNoPropiasScale.level4.total,
    period: "2026",
    summary: "Coordinación y supervisión de cuadrillas de guadañadores y motosierristas en el despeje y mantenimiento de la franja de servidumbre del oleoducto.",
  },
  {
    id: "noprop-l5-soldador",
    code: "NOPROP-N5-SOLD",
    name: "Soldador (No Propias / Mantenimiento Menor)",
    activityType: "no_propias",
    specialty: "soldadura",
    specialtyLabel: "Soldadura",
    level: 5,
    dailyBasicSalary: ocensaNoPropiasScale.level5.basic,
    transportAllowance: ocensaNoPropiasScale.level5.transport,
    foodAllowance: ocensaNoPropiasScale.level5.food,
    totalDailyRate: ocensaNoPropiasScale.level5.total,
    period: "2026",
    summary: "Soldadura estructural para fabricación de rejas, portones perimetrales, barandas de protección, soportes menores y reparaciones locativas de cerramientos.",
  },
  {
    id: "noprop-l5-maestro-civil",
    code: "NOPROP-N5-MAEST",
    name: "Maestro de Obra Civil",
    activityType: "no_propias",
    specialty: "obra_civil",
    specialtyLabel: "Obras Civiles y Estructuras",
    level: 5,
    dailyBasicSalary: ocensaNoPropiasScale.level5.basic,
    transportAllowance: ocensaNoPropiasScale.level5.transport,
    foodAllowance: ocensaNoPropiasScale.level5.food,
    totalDailyRate: ocensaNoPropiasScale.level5.total,
    period: "2026",
    summary: "Dirección técnica en sitio de frentes de obra civil: control de niveles, replanteos, fundición de losas, muros de contención y control de calidad de acabados.",
  },
];

/* ── Funciones de Consulta y Cálculo para APUs ──────────────── */

export function getOcensaLaborPositions(category?: OcensaActivityType): OcensaLaborPosition[] {
  if (!category) return ocensaLaborPositions;
  return ocensaLaborPositions.filter((p) => p.activityType === category);
}

export function getOcensaPositionsBySpecialty(specialty: OcensaSpecialty): OcensaLaborPosition[] {
  return ocensaLaborPositions.filter((p) => p.specialty === specialty);
}

export function getOcensaPositionsByLevel(level: number, category?: OcensaActivityType): OcensaLaborPosition[] {
  return ocensaLaborPositions.filter(
    (p) => p.level === level && (!category || p.activityType === category)
  );
}

/** Calcula el costo total de mano de obra para un puesto dado en días */
export function calculateOcensaLaborCost(
  positionId: string,
  daysWorked: number
): {
  basicSubtotal: number;
  allowancesSubtotal: number;
  totalCost: number;
  position?: OcensaLaborPosition;
} {
  const pos = ocensaLaborPositions.find((p) => p.id === positionId);
  if (!pos) {
    return { basicSubtotal: 0, allowancesSubtotal: 0, totalCost: 0 };
  }
  const basicSubtotal = pos.dailyBasicSalary * daysWorked;
  const allowancesDaily =
    pos.transportAllowance + pos.foodAllowance + (pos.nonSalaryAllowance ?? 0);
  const allowancesSubtotal = allowancesDaily * daysWorked;
  const totalCost = pos.totalDailyRate * daysWorked;

  return { basicSubtotal, allowancesSubtotal, totalCost, position: pos };
}
