"use client";
import { useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
import { isSupabaseConfigured, supabasePublishableKey, supabaseUrl } from "@/lib/supabase/config";
import type { StockProduct } from "@/modules/inventory";

type Props={products:StockProduct[]}; type Line={quantity:string;cost:string};
export function CountsWorkspace({products}:Props){
 const [query,setQuery]=useState("");const [lines,setLines]=useState<Record<string,Line>>({});const [countId,setCountId]=useState("");const [status,setStatus]=useState("");const rows=useMemo(()=>products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())).slice(0,120),[products,query]);
 const client=()=>isSupabaseConfigured&&supabaseUrl&&supabasePublishableKey?createBrowserClient(supabaseUrl,supabasePublishableKey):null;
 async function ensureCount(){if(countId)return countId;const s=client();if(!s||!products[0])throw new Error("No hay conexión o artículos disponibles.");const {data:stock,error:stockError}=await s.from("inventory_stock").select("company_id,branch_id").eq("id",products[0].id).single();if(stockError||!stock)throw stockError||new Error("No se identificó la bodega.");const {data,error}=await s.from("physical_counts").insert({company_id:stock.company_id,branch_id:stock.branch_id,reason:"Carga inicial de inventario"}).select("id").single();if(error||!data)throw error||new Error("No fue posible iniciar la carga.");setCountId(data.id);return data.id;}
 async function saveLine(product:StockProduct){const line=lines[product.id];if(!line||line.quantity==="")return;try{const id=await ensureCount();const s=client();if(!s)return;const {error}=await s.from("physical_count_lines").upsert({count_id:id,stock_id:product.id,system_quantity:product.available,counted_quantity:Number(line.quantity),unit_cost:Number(line.cost||0),reason:"Carga inicial"},{onConflict:"count_id,stock_id"});if(error)throw error;setStatus(`${product.name} guardado.`)}catch(e){setStatus(e instanceof Error?e.message:"No se pudo guardar.")}}
 async function approve(){if(!countId){setStatus("Registra al menos un artículo antes de aprobar.");return;}const pending=Object.keys(lines).length; if(!pending){setStatus("Registra al menos un artículo antes de aprobar.");return;}if(!window.confirm("Se aplicarán las cantidades y costos registrados. Los artículos sin conteo quedarán pendientes y en cero. ¿Continuar?"))return;const s=client();if(!s)return;const {error}=await s.rpc("approve_initial_inventory_count",{target_count:countId});setStatus(error?.message||"Carga inicial aprobada. Inventario actualizado.");}
 return <main className="dashboard-content"><section className="dashboard-heading"><div><p>Operaciones · RFC Enterprise</p><h1>Carga inicial de inventario</h1><small>Registra únicamente lo contado físicamente. Los campos vacíos quedan pendientes, no se convierten en cero.</small></div><button className="inventory-action" onClick={()=>void approve()} type="button">Aprobar carga inicial</button></section><section className="dashboard-panel"><div className="inventory-catalog-controls"><label className="search-field">Buscar artículo<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o SKU"/></label></div><div className="inventory-table-container"><table className="inventory-data-table"><thead><tr><th>Artículo</th><th>Ubicación</th><th>Cantidad física</th><th>Costo unitario COP</th><th>Estado</th></tr></thead><tbody>{rows.map(p=>{const line=lines[p.id]||{quantity:"",cost:""};return <tr key={p.id}><td><strong>{p.name}</strong><small>{p.sku} · {p.unit}</small></td><td>{p.location}</td><td><input aria-label={`Cantidad de ${p.name}`} type="number" min="0" step="any" value={line.quantity} onChange={e=>setLines(v=>({...v,[p.id]:{...line,quantity:e.target.value}}))} onBlur={()=>void saveLine(p)}/></td><td><input aria-label={`Costo de ${p.name}`} type="number" min="0" step="any" value={line.cost} onChange={e=>setLines(v=>({...v,[p.id]:{...line,cost:e.target.value}}))} onBlur={()=>void saveLine(p)}/></td><td>{line.quantity===""?"Pendiente":"Guardado"}</td></tr>})}</tbody></table></div><p className="panel-intro">{status||`Mostrando ${rows.length} artículos. Busca y registra por ubicación para continuar.`}</p></section></main>;
}
