-- RFC Enterprise v0.1. Apply in Supabase SQL Editor, then run `supabase db pull`.
create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public;
create type public.inventory_movement_type as enum ('entry','exit','adjustment_in','adjustment_out');

create table public.companies (id uuid primary key default gen_random_uuid(),slug text not null unique check(slug ~ '^[a-z0-9-]+$'),name text not null,tax_id text unique,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.branches (id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete restrict,code text not null,name text not null,address text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,code));
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade,display_name text,email text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.roles (id uuid primary key default gen_random_uuid(),code text not null unique check(code ~ '^[a-z0-9_.-]+$'),name text not null,description text,created_at timestamptz not null default now());
create table public.permissions (id uuid primary key default gen_random_uuid(),code text not null unique check(code ~ '^[a-z0-9_.-]+$'),name text not null,description text,created_at timestamptz not null default now());
create table public.role_permissions (role_id uuid not null references public.roles(id) on delete cascade,permission_id uuid not null references public.permissions(id) on delete cascade,primary key(role_id,permission_id));
create table public.user_roles (user_id uuid not null references public.profiles(id) on delete cascade,role_id uuid not null references public.roles(id) on delete cascade,company_id uuid not null references public.companies(id) on delete cascade,branch_id uuid references public.branches(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,role_id,company_id,branch_id));
create table public.app_modules (id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,route text not null,is_enabled boolean not null default true,sort_order integer not null default 0);
create table public.company_modules (company_id uuid not null references public.companies(id) on delete cascade,module_id uuid not null references public.app_modules(id) on delete cascade,is_enabled boolean not null default true,primary key(company_id,module_id));
create table public.company_settings (company_id uuid not null references public.companies(id) on delete cascade,key text not null,value jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now(),primary key(company_id,key));
create table public.audit_logs (id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),branch_id uuid references public.branches(id),actor_id uuid references public.profiles(id) on delete set null,entity_type text not null,entity_id uuid,action text not null,before_data jsonb,after_data jsonb,created_at timestamptz not null default now());
create table public.inventory_items (id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),sku text,name text not null,category text,brand text,unit text not null default 'unidad',notes text,source_group text,source_row integer,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique nulls not distinct(company_id,source_group,source_row));
create table public.inventory_stock (id uuid primary key default gen_random_uuid(),item_id uuid not null references public.inventory_items(id),company_id uuid not null references public.companies(id),branch_id uuid not null references public.branches(id),inventory_group text not null check(inventory_group in('bodega','dotacion','trabajadores')),location text,quantity numeric(14,3) not null default 0 check(quantity >= 0),minimum_quantity numeric(14,3),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique nulls not distinct(item_id,branch_id,inventory_group,location));
create table public.inventory_movements (id uuid primary key default gen_random_uuid(),stock_id uuid not null references public.inventory_stock(id),company_id uuid not null references public.companies(id),branch_id uuid not null references public.branches(id),movement_type public.inventory_movement_type not null,quantity numeric(14,3) not null check(quantity > 0),reference text not null,notes text,occurred_at timestamptz not null default now(),created_by uuid references public.profiles(id) on delete set null default auth.uid(),created_at timestamptz not null default now());

create index branches_company_idx on public.branches(company_id);create index user_roles_user_company_idx on public.user_roles(user_id,company_id);create index items_company_name_idx on public.inventory_items(company_id,name);create index stock_branch_group_idx on public.inventory_stock(branch_id,inventory_group);create index movements_stock_date_idx on public.inventory_movements(stock_id,occurred_at desc);create index audit_company_date_idx on public.audit_logs(company_id,created_at desc);
create function private.set_updated_at() returns trigger language plpgsql set search_path=public as $$begin new.updated_at=now();return new;end;$$;
create function private.handle_new_user() returns trigger language plpgsql security definer set search_path=public,auth as $$begin insert into public.profiles(id,display_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',new.email),new.email) on conflict(id) do nothing;return new;end;$$;
create function private.apply_inventory_movement() returns trigger language plpgsql set search_path=public as $$declare delta numeric(14,3);begin select case new.movement_type when 'entry' then new.quantity when 'adjustment_in' then new.quantity else -new.quantity end into delta;update public.inventory_stock set quantity=quantity+delta where id=new.stock_id and company_id=new.company_id and branch_id=new.branch_id;if not found then raise exception 'El movimiento no corresponde a la existencia seleccionada';end if;return new;end;$$;
create trigger companies_updated before update on public.companies for each row execute function private.set_updated_at();create trigger branches_updated before update on public.branches for each row execute function private.set_updated_at();create trigger profiles_updated before update on public.profiles for each row execute function private.set_updated_at();create trigger items_updated before update on public.inventory_items for each row execute function private.set_updated_at();create trigger stock_updated before update on public.inventory_stock for each row execute function private.set_updated_at();create trigger auth_user_profile after insert on auth.users for each row execute function private.handle_new_user();create trigger movement_updates_stock before insert on public.inventory_movements for each row execute function private.apply_inventory_movement();

insert into public.companies(slug,name) values('rfc','Representaciones Figueroa Castro S.A.S.') on conflict(slug) do nothing;insert into public.branches(company_id,code,name,address) select id,'caucasia','Caucasia','Calle 29 K #27-62, Caucasia, Antioquia' from public.companies where slug='rfc' on conflict(company_id,code) do nothing;insert into public.roles(code,name,description) values('administrator','Administrador','Administración completa.'),('inventory_manager','Responsable de inventario','Gestiona existencias y movimientos.'),('inventory_viewer','Consulta de inventario','Consulta existencias y movimientos.') on conflict(code) do nothing;insert into public.permissions(code,name) values('core.settings.read','Consultar configuración'),('core.settings.manage','Gestionar configuración'),('inventory.items.read','Consultar artículos'),('inventory.items.manage','Gestionar artículos'),('inventory.stock.read','Consultar existencias'),('inventory.movements.read','Consultar movimientos'),('inventory.movements.create','Registrar movimientos'),('inventory.reports.read','Consultar reportes') on conflict(code) do nothing;insert into public.app_modules(code,name,route,sort_order) values('core','Administración','/dashboard',0),('inventory','Inventarios','/inventory',10) on conflict(code) do nothing;insert into public.company_modules(company_id,module_id) select c.id,m.id from public.companies c cross join public.app_modules m where c.slug='rfc' on conflict do nothing;

alter table public.companies enable row level security;alter table public.branches enable row level security;alter table public.profiles enable row level security;alter table public.roles enable row level security;alter table public.permissions enable row level security;alter table public.role_permissions enable row level security;alter table public.user_roles enable row level security;alter table public.app_modules enable row level security;alter table public.company_modules enable row level security;alter table public.company_settings enable row level security;alter table public.audit_logs enable row level security;alter table public.inventory_items enable row level security;alter table public.inventory_stock enable row level security;alter table public.inventory_movements enable row level security;
create policy profiles_self_read on public.profiles for select to authenticated using((select auth.uid())=id);create policy profiles_self_update on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);create policy roles_read on public.roles for select to authenticated using(true);create policy permissions_read on public.permissions for select to authenticated using(true);create policy role_permissions_read on public.role_permissions for select to authenticated using(true);create policy user_roles_self_read on public.user_roles for select to authenticated using((select auth.uid())=user_id);create policy modules_read on public.app_modules for select to authenticated using(true);
create policy companies_member_read on public.companies for select to authenticated using(exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.company_id=companies.id));create policy branches_member_read on public.branches for select to authenticated using(exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.company_id=branches.company_id));create policy company_modules_member_read on public.company_modules for select to authenticated using(exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.company_id=company_modules.company_id));create policy settings_member_read on public.company_settings for select to authenticated using(exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.company_id=company_settings.company_id));create policy audit_member_read on public.audit_logs for select to authenticated using(exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.company_id=audit_logs.company_id));create policy items_member_read on public.inventory_items for select to authenticated using(exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.company_id=inventory_items.company_id));create policy stock_member_read on public.inventory_stock for select to authenticated using(exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.company_id=inventory_stock.company_id));create policy movements_member_read on public.inventory_movements for select to authenticated using(exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.company_id=inventory_movements.company_id));create policy movements_manager_insert on public.inventory_movements for insert to authenticated with check(exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=(select auth.uid()) and ur.company_id=inventory_movements.company_id and r.code in('administrator','inventory_manager')));create policy stock_manager_update on public.inventory_stock for update to authenticated using(exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=(select auth.uid()) and ur.company_id=inventory_stock.company_id and r.code in('administrator','inventory_manager'))) with check(exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=(select auth.uid()) and ur.company_id=inventory_stock.company_id and r.code in('administrator','inventory_manager')));
