/* Transcripcion de la tabla oficial de OCENSA AEX-INS-006 v26, leida de
 * las capturas de las dos paginas del documento.
 *
 * Regla de separacion: dentro de una celda los cargos van separados por
 * punto y coma y, cuando comparten equipo, por coma. Cada uno es un cargo
 * distinto con el mismo nivel y el mismo salario. */

export const ocensaOficialesPropias: Record<number, string[]> = {
  1: [
    "Operador Planta Eléctrica",
    "Marinero Costanero de Cubierta",
    "Conductor de Vehículo Liviano y/o Pasajeros",
    "Oficinista 2",
    "Obrero",
    "Controlador de Tráfico / Paletero",
    "Auxiliar Servicios Generales",
    "Apunta Tiempo",
    "Motosierrista",
    "Operador Motobomba",
    "Hidro Lavadora y Electrobomba",
    "Operador de Rana; Martillo; Chapola",
  ],
  2: [
    "Ayudante Electricista",
    "Ayudante Instrumentación",
    "Ayudante Mecánico Off Shore",
    "Conector Off Shore",
    "Marinero de Cubierta",
    "Marinero Operador",
    "Camarero",
    "Marinero AB de Embarcación",
    "Marinero Ajustador de Bridas",
    "Ayudante de Mecánica",
    "Ayudante Pailería",
    "Ayudante Tubería",
    "Ayudante Cadenero",
    "Ayudante de Pintura",
    "Ayudante de Bodega o Bodeguero",
    "Conductor de Vehículo Pesado Propio de la Industria de Más de 3 Ton",
    "Socorrista",
    "Conductor de Ambulancia",
    "Campamentero",
    "Ayudante Torque",
    "Tolvero",
    "Portaprisma",
    "Ayudante Soldadura",
  ],
  3: [
    "Buzo Segunda",
    "Mecánico Off Shore",
    "Marinero Timonel",
    "Marinero de Máquinas",
    "Marinero Cocinero (Embarcaciones Mayores)",
    "Oficial I",
    "Pintor",
    "Vigía HSE",
    "Oficinista 1",
    "Sandblastero",
    "Sandblastero Pintor",
    "Oficial",
    "Auxiliar Materiales",
    "Conductor de Vehículo Pesado Propio de la Industria de Más de 3 Ton",
    "Auxiliar de Enfermería",
    "Operador Grúa hasta 40 Ton",
    "Aparejador",
    "Operador de Motoniveladora",
    "Retroexcavadora",
    "Vibrocompactador",
    "Auxiliar Ambiental",
    "Analista de Gestión de Mantenimiento",
    "Esmerilador",
  ],
  4: [
    "Electricista 1",
    "Instrumentista 1",
    "Oficial Puente Regional hasta 2800 TRB",
    "Mecánico 1",
    "Pailero 1",
    "Tubero 1",
    "Montador 1",
    "Cadenero 1",
    "Documentador",
    "Almacenista",
    "Operador Equipo Pesado 1",
    "Andamiero 1",
    "Operador de Grúa hasta 90 Ton",
    "Operador de Retroexcavadora",
    "Operador Bobcat",
    "Operador Man Lift",
    "Operador de Herramientas Especiales",
    "Operador Sideboom",
    "Operador Camabaja/Alta",
    "Electromecánico",
    "Operador Camión Grúa",
    "Operador Planta de Concreto",
    "Operador de Equipo de Perforación con Manejo de Explosivos",
    "Operador de Herramientas de Torque",
    "Auxiliar Ambiental",
    "Operador de Equipo Pruebas Hidrostáticas",
    "Operador Montacargas",
    "Operador Cargador",
    "Operador Retrollantas",
    "Operador Carromacho",
    "Operador Camión de Vacío",
    "Doblador",
  ],
  5: [
    "Electricista 1A",
    "Instrumentista 1A",
    "Contramaestre AB Embarcación",
    "Oficial Puente hasta 3000 TRB",
    "Oficial de Máquinas hasta 3000 KW",
    "Mecánico 1A",
    "Pailero 1A",
    "Tubero 1A",
    "Montador 1A",
    "Alineador de Tuberías",
    "Rescatista de Alturas",
    "Operador de Equipo Pesado 1A",
    "Andamiero 1A",
    "Laboratorista",
  ],
  6: [
    "Oficial de Puente",
    "Inspector HSE; Ambiental",
    "Operador de Grúa mayor a 80 Ton",
    "Enfermera Profesional",
    "Topógrafo QA/QC; Calidad y Cantidad",
    "Capataz",
  ],
};

/* La tabla de no propias viene en filas separadas, una por oficio. */
export const ocensaOficialesNoPropias: Record<number, string[]> = {
  1: [
    "Obrero",
    "Obrero Descontaminación",
    "Camarera",
    "Auxiliar de Aseo y Cafetería",
    "Mesero",
    "Ayudante MTTO Vehículos",
    "Jardinero",
    "Obrero Apicultor y Fumigador",
    "Señalizador Vial",
    "Mensajero",
    "Recepcionista",
  ],
  2: [
    "Obrero con Experiencia",
    "Ayudante de Obra Civil",
    "Conductor",
    "Auxiliar de Inventarios",
    "Rescatista de Alturas",
    "Técnico Gestión Documental / Auxiliar",
    "Guadañador",
    "Aparejador de Grúa",
    "Aparejador de Cargas",
    "Aparejador de Equipos de Izaje",
  ],
  3: ["Vigilante"],
  4: [
    "Albañil",
    "Oficial de Construcción",
    "Operador Vehículo Pesado",
    "Ayudante Eléctrico",
    "Ayudante Mecánico",
    "Ayudante Soldadura",
    "Instrumentista",
    "Técnico Electricista",
    "Capataz de Zonas Verdes y Rocería",
    "Oficial de Obra Civil",
  ],
  5: ["Soldador", "Maestro de Obra Civil"],
};

/* Salarios oficiales publicados en el documento. */
export const ocensaSalariosNoPropias: Record<number, number> = {
  1: 60581,
  2: 64750,
  3: 77100,
  4: 79924,
  5: 112890,
};

export const ocensaSalariosPropias: Record<number, number> = {
  1: 114854,
  2: 132707,
  3: 139630,
  4: 164879,
  5: 184864,
  6: 203065,
};

/* Nota al pie del documento: los oficios marcados con asterisco son
   cargos nuevos de esta version. Si por razones financieras o
   contractuales no se cambia de inmediato, deben surtirse en la siguiente
   prorroga o contrato nuevo. */
export const ocensaCargosNuevosNoPropias = [
  "Obrero Apicultor y Fumigador",
  "Señalizador Vial",
  "Mensajero",
  "Recepcionista",
  "Técnico Gestión Documental / Auxiliar",
  "Guadañador",
  "Aparejador de Grúa",
  "Aparejador de Cargas",
  "Aparejador de Equipos de Izaje",
  "Ayudante Soldadura",
  "Técnico Electricista",
  "Capataz de Zonas Verdes y Rocería",
  "Oficial de Obra Civil",
  "Soldador",
  "Maestro de Obra Civil",
];