export type ApuActivity = { name: string; unit: string; group: string };

export const apuActivities: ApuActivity[] = [
  { group: "Preliminares", name: "Localización y replanteo", unit: "m²" },
  { group: "Preliminares", name: "Cerramiento provisional de obra", unit: "m" },
  { group: "Preliminares", name: "Campamento y señalización de obra", unit: "gl" },
  { group: "Preliminares", name: "Limpieza y descapote manual", unit: "m²" },
  { group: "Preliminares", name: "Demolición de concreto", unit: "m³" },
  { group: "Preliminares", name: "Demolición de muro", unit: "m²" },
  { group: "Movimiento de tierras", name: "Excavación manual", unit: "m³" },
  { group: "Movimiento de tierras", name: "Excavación mecánica", unit: "m³" },
  { group: "Movimiento de tierras", name: "Relleno compactado con material seleccionado", unit: "m³" },
  { group: "Movimiento de tierras", name: "Retiro y disposición de sobrantes", unit: "m³" },
  { group: "Concreto", name: "Concreto de limpieza 2000 psi", unit: "m³" },
  { group: "Concreto", name: "Concreto para zapatas 3000 psi", unit: "m³" },
  { group: "Concreto", name: "Concreto para vigas y columnas 3000 psi", unit: "m³" },
  { group: "Concreto", name: "Acero de refuerzo figurado e instalado", unit: "kg" },
  { group: "Concreto", name: "Formaleta para concreto", unit: "m²" },
  { group: "Mampostería", name: "Muro en bloque de cemento", unit: "m²" },
  { group: "Mampostería", name: "Muro en ladrillo estructural", unit: "m²" },
  { group: "Mampostería", name: "Pañete liso de muros", unit: "m²" },
  { group: "Mampostería", name: "Estuco y pintura de muros", unit: "m²" },
  { group: "Cubiertas", name: "Estructura metálica para cubierta", unit: "kg" },
  { group: "Cubiertas", name: "Suministro e instalación de teja termoacústica", unit: "m²" },
  { group: "Cubiertas", name: "Canal y bajante de aguas lluvias", unit: "m" },
  { group: "Pisos y acabados", name: "Piso en concreto afinado", unit: "m²" },
  { group: "Pisos y acabados", name: "Enchape cerámico de piso", unit: "m²" },
  { group: "Pisos y acabados", name: "Enchape cerámico de muro", unit: "m²" },
  { group: "Hidrosanitarias", name: "Punto hidráulico de agua fría", unit: "und" },
  { group: "Hidrosanitarias", name: "Punto sanitario PVC", unit: "und" },
  { group: "Hidrosanitarias", name: "Instalación de sanitario", unit: "und" },
  { group: "Hidrosanitarias", name: "Instalación de lavamanos", unit: "und" },
  { group: "Eléctricas", name: "Punto eléctrico de iluminación", unit: "und" },
  { group: "Eléctricas", name: "Punto eléctrico de tomacorriente", unit: "und" },
  { group: "Eléctricas", name: "Canalización eléctrica PVC", unit: "m" },
  { group: "Eléctricas", name: "Tablero eléctrico y protecciones", unit: "und" },
  { group: "Metalmecánica", name: "Fabricación e instalación de estructura metálica", unit: "kg" },
  { group: "Metalmecánica", name: "Fabricación e instalación de baranda metálica", unit: "m" },
  { group: "Metalmecánica", name: "Pintura anticorrosiva de estructura metálica", unit: "m²" },
  { group: "Vías y exteriores", name: "Subbase granular compactada", unit: "m³" },
  { group: "Vías y exteriores", name: "Placa huella en concreto", unit: "m²" },
  { group: "Vías y exteriores", name: "Andén en concreto", unit: "m²" },
  { group: "Ambiental y SST", name: "Plan de manejo de residuos de obra", unit: "gl" },
  { group: "Ambiental y SST", name: "Señalización y demarcación de seguridad", unit: "gl" },
];
