-- Completes the official job catalogue by level for CENIT 2026 and ODC 2025.
-- OCENSA roles are already covered by its 68-position catalogue from AEX-INS-006.
-- This only maps positions to existing official levels; it never changes published salary values.

with official_roles (client_name, level, sort_order, name) as (
  values
    ('CENIT', 2, 1, 'Auxiliar De Cargue Y Descargue De Descargadero Carrotanques'),
    ('CENIT', 3, 1, 'Operador Facilidades De Superficie'),
    ('CENIT', 4, 1, 'Operador De Cargue Y Descargue Carrotanques'),
    ('CENIT', 5, 1, 'Alineador - Tubero'),
    ('CENIT', 2, 2, 'Operador de Planta En Entrenamiento (Sin Experiencia)'),
    ('CENIT', 3, 2, 'Ayudante Técnico De Soldadura'),
    ('CENIT', 4, 2, 'Operador De Planta'),
    ('CENIT', 5, 2, 'Aparejador Mecánico'),
    ('CENIT', 2, 3, 'Marinero Costanero De Cubierta'),
    ('CENIT', 3, 3, 'Ayudante Técnico Pailería'),
    ('CENIT', 4, 3, 'Técnico Operador'),
    ('CENIT', 5, 3, 'Montador 1'),
    ('CENIT', 2, 4, 'Apunta Tiempo'),
    ('CENIT', 3, 4, 'Ayudante Técnico Tubería'),
    ('CENIT', 4, 4, 'Esmerilador'),
    ('CENIT', 5, 4, 'Operador Pipe Walder'),
    ('CENIT', 2, 5, 'Asistente Administrativo'),
    ('CENIT', 3, 5, 'Biselador'),
    ('CENIT', 4, 5, 'Técnico Electricista'),
    ('CENIT', 5, 5, 'Pailero 1'),
    ('CENIT', 2, 6, 'Auxiliar Servicios Generales 1'),
    ('CENIT', 3, 6, 'Marinero Camarero'),
    ('CENIT', 4, 6, 'Técnico Instrumentación Y Control'),
    ('CENIT', 5, 6, 'Soldador 1'),
    ('CENIT', 2, 7, 'Ayudante De Camión De Vacio'),
    ('CENIT', 3, 7, 'Conector Off Shore'),
    ('CENIT', 4, 7, 'Buzo Segunda'),
    ('CENIT', 5, 7, 'Tubero 1'),
    ('CENIT', 3, 8, 'Cubierta Ayudante Mecánico Off Shore'),
    ('CENIT', 4, 8, 'Maquinista (Embarcaciones Mayores)'),
    ('CENIT', 5, 8, 'Técnico Electricista 1'),
    ('CENIT', 3, 9, 'Marinero Ab De Embarcación'),
    ('CENIT', 4, 9, 'Marinero Cocinero (Embarcaciones Mayores)'),
    ('CENIT', 5, 9, 'Técnico Instrumentación y Control 1'),
    ('CENIT', 3, 10, 'Marinero Ajustador De Bridas'),
    ('CENIT', 4, 10, 'Marinero De Máquinas'),
    ('CENIT', 5, 10, 'Buzo Industrial'),
    ('CENIT', 3, 11, 'Marinero De Cubierta'),
    ('CENIT', 4, 11, 'Marinero Timonel'),
    ('CENIT', 5, 11, 'Oficial Puente Regional Hasta 2800 TRB'),
    ('CENIT', 3, 12, 'Marinero Operador'),
    ('CENIT', 4, 12, 'Mecánico (Embarcaciones Mayores)'),
    ('CENIT', 5, 12, 'Técnico Electromecánico'),
    ('CENIT', 3, 13, 'Patrón de Bote / Motorista Costanero'),
    ('CENIT', 4, 13, 'Mecánico Off Shore'),
    ('CENIT', 5, 13, 'Técnico Mecánico 1'),
    ('CENIT', 3, 14, 'Aparejador De Carga Grúa De Hasta 30 Toneladas'),
    ('CENIT', 4, 14, 'Oficial 1'),
    ('CENIT', 5, 14, 'Técnico 1 De Inspección De Tubulares En Superficie Que'),
    ('CENIT', 3, 15, 'Auxiliar De Logística'),
    ('CENIT', 4, 15, 'Técnico (Embarcaciones Mayores)'),
    ('CENIT', 5, 15, 'Analista De Hidrocarburos Y Agua'),
    ('CENIT', 3, 16, 'Auxiliar De Materiales 2'),
    ('CENIT', 4, 16, 'Técnico Mecánico'),
    ('CENIT', 5, 16, 'Almacenista'),
    ('CENIT', 3, 17, 'Auxiliar Servicios Generales 2'),
    ('CENIT', 4, 17, 'Técnico De Inspección De Tubulares En Superficie Que Incluye Línea De Flujo Y Vasijas (Como Tanques)'),
    ('CENIT', 5, 17, 'Andamiero 1'),
    ('CENIT', 3, 18, 'Ayudante Técnico Electricista'),
    ('CENIT', 4, 18, 'Albañil'),
    ('CENIT', 5, 18, 'Auxiliar Ambiental 1'),
    ('CENIT', 3, 19, 'Ayudante Técnico Instrumentación Y Control'),
    ('CENIT', 4, 19, 'Aislador Térmico'),
    ('CENIT', 5, 19, 'Cadenero 1'),
    ('CENIT', 3, 20, 'Ayudante Técnico Mecánico'),
    ('CENIT', 4, 20, 'Analista De Gestión De Mantenimiento'),
    ('CENIT', 4, 21, 'Aparejador'),
    ('CENIT', 2, 8, 'Ayudante De Lanchero'),
    ('CENIT', 3, 21, 'Ayudante De Bodega O Bodeguero'),
    ('CENIT', 4, 22, 'Auxiliar Ambiental'),
    ('CENIT', 5, 20, 'Doblador'),
    ('CENIT', 2, 9, 'Ayudante De Reparaciones'),
    ('CENIT', 3, 22, 'Ayudante De Cadenero'),
    ('CENIT', 4, 23, 'Auxiliar De Enfermería'),
    ('CENIT', 5, 21, 'Documentador'),
    ('CENIT', 2, 10, 'Controlador De Tráfico / Paletero Funcionario Apoyo A La Operación'),
    ('CENIT', 3, 23, 'Ayudante De Obra Civil Ayudante Qa/Qc'),
    ('CENIT', 4, 24, 'Auxiliar Materiales 1 Granallador'),
    ('CENIT', 5, 22, 'Operador De Herramientas Especiales Lintero'),
    ('CENIT', 2, 11, 'Obrero'),
    ('CENIT', 3, 24, 'Ayudante Técnico'),
    ('CENIT', 4, 25, 'Oficinista 1'),
    ('CENIT', 5, 23, 'Operador Bobcat'),
    ('CENIT', 2, 12, 'Operador De Equipos (Planta Eléctrica, Motobomba Hidrolavadora Electro-Bomba, Motosierrista)'),
    ('CENIT', 3, 25, 'Ayudante Técnico De Albañilería'),
    ('CENIT', 4, 26, 'Operador De Retrocargador, Vibrocompactador'),
    ('CENIT', 5, 24, 'Operador De Tracto Camión Cama-baja O Cama-alta'),
    ('CENIT', 2, 13, 'Operador De Rana, Martillo, Chapola'),
    ('CENIT', 3, 26, 'Ayudante Técnico de Rocería'),
    ('CENIT', 4, 27, 'Operador Finisher'),
    ('CENIT', 5, 25, 'Operador Camión De Vacío'),
    ('CENIT', 2, 14, 'Patiero Ayudante De Pintura'),
    ('CENIT', 3, 27, 'Ayudante Torque Cadenero'),
    ('CENIT', 4, 28, 'Operador Grúa Hasta 40 Ton Sandblastero'),
    ('CENIT', 5, 26, 'Operador Camión Grúa Operador Cargador'),
    ('CENIT', 3, 28, 'Campamentero'),
    ('CENIT', 4, 29, 'Pintor Sandblasting'),
    ('CENIT', 5, 27, 'Operador Carromacho'),
    ('CENIT', 3, 29, 'Mecánico De Automotores / Maquinaria'),
    ('CENIT', 4, 30, 'Vigía HSE'),
    ('CENIT', 5, 28, 'Operador De Equipo De Perforación Con Manejo De Explosivos'),
    ('CENIT', 3, 30, 'Operador Compresor'),
    ('CENIT', 4, 31, 'Oficial De Obra Civil'),
    ('CENIT', 5, 29, 'Operador De Equipo Pruebas Hidrostáticas'),
    ('CENIT', 3, 31, 'Operador De Bomba Neumática'),
    ('CENIT', 4, 32, 'Capataz'),
    ('CENIT', 5, 30, 'Operador De Grúa Hasta 70 Ton'),
    ('CENIT', 3, 32, 'Operador De Calderas'),
    ('CENIT', 4, 33, 'Conductor De Volquetas Y Camiones'),
    ('CENIT', 5, 31, 'Operador De Herramientas De Torque'),
    ('CENIT', 3, 33, 'Operador De Descargue'),
    ('CENIT', 4, 34, 'Conductor Vehículo Pesado Propio De La Industria De Más De 3 Ton'),
    ('CENIT', 5, 32, 'Operador De Retroexcavadora Cadena'),
    ('CENIT', 3, 34, 'Operador De Equipos Centrifugación'),
    ('CENIT', 5, 33, 'Operador De Soldadura Mecanizada'),
    ('CENIT', 3, 35, 'Portaprisma'),
    ('CENIT', 5, 34, 'Operador De Vibrocompactador Mayor A 5 Ton'),
    ('CENIT', 3, 36, 'Rescatista / Socorrista'),
    ('CENIT', 5, 35, 'Operador Equipo Pesado 1'),
    ('CENIT', 3, 37, 'Tolvero'),
    ('CENIT', 5, 36, 'Operador Man Lift'),
    ('CENIT', 3, 38, 'Lanchero'),
    ('CENIT', 5, 37, 'Operador Montacargas'),
    ('CENIT', 3, 39, 'Pintor'),
    ('CENIT', 5, 38, 'Operador Planta De Concreto'),
    ('CENIT', 3, 40, 'Conductor de Ambulancia'),
    ('CENIT', 5, 39, 'Operador Retro De Grúa'),
    ('CENIT', 5, 40, 'Operador Retrollantas'),
    ('CENIT', 5, 41, 'Operador Sideboom'),
    ('CENIT', 5, 42, 'Operador Tractomula'),
    ('CENIT', 5, 43, 'Refractarista'),
    ('CENIT', 5, 44, 'Refractarista Lanzador'),
    ('CENIT', 5, 45, 'Soldador De Revestimiento'),
    ('ODC', 1, 1, 'Ayudante de Reparaciones'),
    ('ODC', 2, 1, 'Ayudante de Bodega o Bodeguero'),
    ('ODC', 3, 1, 'Auxiliar Ambiental'),
    ('ODC', 4, 1, 'Doblador'),
    ('ODC', 5, 1, 'Operador Equipo Pesado 1A'),
    ('ODC', 1, 2, 'Controlador de Tráfico / Paletero'),
    ('ODC', 2, 2, 'Ayudante de Cadenero'),
    ('ODC', 3, 2, 'Auxiliar de Enfermería'),
    ('ODC', 4, 2, 'Documentador'),
    ('ODC', 5, 2, 'Operador Grúa Mayor A 70 Ton'),
    ('ODC', 1, 3, 'Obrero'),
    ('ODC', 2, 3, 'Ayudante de Obra Civil'),
    ('ODC', 3, 3, 'Auxiliar Materiales 1'),
    ('ODC', 4, 3, 'Operador de Herramientas Especiales'),
    ('ODC', 5, 3, 'Rescatistas de Alturas'),
    ('ODC', 1, 4, 'Operador de Equipos (Planta Eléctrica, Motobomba Hidro lavadora Electro-Bomba, Motosierrista)'),
    ('ODC', 2, 4, 'Ayudante Qa/Qc'),
    ('ODC', 3, 4, 'Granallador'),
    ('ODC', 4, 4, 'Operador Bobcat'),
    ('ODC', 5, 4, 'Técnico Especializado Ambiental'),
    ('ODC', 1, 5, 'Operador de Rana, Martillo, Chapola'),
    ('ODC', 2, 5, 'Ayudante Técnico'),
    ('ODC', 3, 5, 'Oficinista 1'),
    ('ODC', 4, 5, 'Operador de Tracto Camión Cama-baja O Cama-alta'),
    ('ODC', 5, 5, 'Alineador de tubería'),
    ('ODC', 1, 6, 'Patiero'),
    ('ODC', 2, 6, 'Ayudante Técnico de Albañilería'),
    ('ODC', 3, 6, 'Operador de Retrocargador, Vibro compactador'),
    ('ODC', 4, 6, 'Operador Camión de Vacío'),
    ('ODC', 5, 6, 'Montador 1A'),
    ('ODC', 1, 7, 'Ayudante de Pintura'),
    ('ODC', 2, 7, 'Ayudante Técnico de Rocería'),
    ('ODC', 3, 7, 'Operador Grúa Hasta 40 Ton'),
    ('ODC', 4, 7, 'Operador Camión Grúa'),
    ('ODC', 5, 7, 'Pailero 1A'),
    ('ODC', 1, 8, 'Ayudante técnico electricista'),
    ('ODC', 2, 8, 'Ayudante Torque'),
    ('ODC', 3, 8, 'Sandblastero'),
    ('ODC', 4, 8, 'Operador Cargador'),
    ('ODC', 5, 8, 'Soldador 1A'),
    ('ODC', 1, 9, 'Ayudante técnico instrumentación y control'),
    ('ODC', 2, 9, 'Cadenero'),
    ('ODC', 3, 9, 'Pintor Sandblasting'),
    ('ODC', 4, 9, 'Operador Carro macho'),
    ('ODC', 5, 9, 'Soldador Argonero'),
    ('ODC', 1, 10, 'Ayudante técnico mecánico'),
    ('ODC', 2, 10, 'Campamentero'),
    ('ODC', 3, 10, 'Vigía HSE'),
    ('ODC', 4, 10, 'Operador de Equipo Pruebas Hidrostáticas'),
    ('ODC', 5, 10, 'Tubero 1A'),
    ('ODC', 1, 11, 'Apunta tiempo'),
    ('ODC', 2, 11, 'Mecánico de Automotores / Maquinaria'),
    ('ODC', 3, 11, 'Oficial de Obra Civil'),
    ('ODC', 4, 11, 'Operador de Grúa Hasta 70 Ton'),
    ('ODC', 5, 11, 'Técnico electricista 1A'),
    ('ODC', 1, 12, 'Asistente administrativo'),
    ('ODC', 2, 12, 'Operador Compresor'),
    ('ODC', 3, 12, 'Capataz'),
    ('ODC', 4, 12, 'Operador de Herramientas de Torque'),
    ('ODC', 5, 12, 'Técnico instrumentación y control 1A'),
    ('ODC', 1, 13, 'Auxiliar servicios generales 1'),
    ('ODC', 2, 13, 'Operador de Bomba Neumática'),
    ('ODC', 3, 13, 'Conductor de Volquetas y Camiones'),
    ('ODC', 4, 13, 'Operador de Retroexcavadora Cadena'),
    ('ODC', 5, 13, 'Técnico Mecánico 1A'),
    ('ODC', 1, 14, 'Ayudante de camión de vacío'),
    ('ODC', 2, 14, 'Porta prisma'),
    ('ODC', 3, 14, 'Conductor Vehículo Pesado Propio de la Industria de más de 3 Ton'),
    ('ODC', 4, 14, 'Operador de Soldadura Mecanizada'),
    ('ODC', 5, 14, 'Andamiero 1A'),
    ('ODC', 2, 15, 'Rescatista / Socorrista'),
    ('ODC', 3, 15, 'Operador de cargue y descargue de carrotanques'),
    ('ODC', 4, 15, 'Operador de Vibro compactador Mayor A 5 Ton'),
    ('ODC', 5, 15, 'Laboratorista'),
    ('ODC', 2, 16, 'Conductor de Ambulancia'),
    ('ODC', 3, 16, 'Esmerilador'),
    ('ODC', 4, 16, 'Operador Equipo Pesado 1'),
    ('ODC', 5, 16, 'Operador de Buldozer'),
    ('ODC', 2, 17, 'Tolvero'),
    ('ODC', 3, 17, 'Técnico electricista'),
    ('ODC', 4, 17, 'Operador Man Lift'),
    ('ODC', 5, 17, 'Operador de Motoniveladora'),
    ('ODC', 2, 18, 'Pintor'),
    ('ODC', 3, 18, 'Técnico instrumentación y control'),
    ('ODC', 4, 18, 'Operador Montacargas'),
    ('ODC', 2, 19, 'Ayudante técnico de soldadura'),
    ('ODC', 3, 19, 'Oficial 1'),
    ('ODC', 4, 19, 'Operador Planta de Concreto'),
    ('ODC', 2, 20, 'Ayudante técnico pailería'),
    ('ODC', 3, 20, 'Técnico Mecánico'),
    ('ODC', 4, 20, 'Operador Retro de Grúa'),
    ('ODC', 2, 21, 'Ayudante técnico tubería'),
    ('ODC', 3, 21, 'Albañil'),
    ('ODC', 4, 21, 'Operador Retro llantas'),
    ('ODC', 2, 22, 'Biselador'),
    ('ODC', 3, 22, 'Aislador térmico'),
    ('ODC', 4, 22, 'Operador Sideboom'),
    ('ODC', 2, 23, 'Aparejador de carga grúa de hasta 30 Ton'),
    ('ODC', 3, 23, 'Analista de gestión de mantenimiento'),
    ('ODC', 4, 23, 'Operador Tractomula'),
    ('ODC', 2, 24, 'Auxiliar de logística'),
    ('ODC', 3, 24, 'Aparejador'),
    ('ODC', 4, 24, 'Soldador de Revestimiento'),
    ('ODC', 2, 25, 'Auxiliar de materiales 2'),
    ('ODC', 4, 25, 'Alineador-Tubero'),
    ('ODC', 2, 26, 'Auxiliar Servicios generales 2'),
    ('ODC', 4, 26, 'Aparejador-Mecánico'),
    ('ODC', 4, 27, 'Montador 1'),
    ('ODC', 4, 28, 'Operador Pipe Walder'),
    ('ODC', 4, 29, 'Pailero 1'),
    ('ODC', 4, 30, 'Soldador 1'),
    ('ODC', 4, 31, 'Tubero 1'),
    ('ODC', 4, 32, 'Técnico electricista 1'),
    ('ODC', 4, 33, 'Técnico instrumentación y control 1'),
    ('ODC', 4, 34, 'Técnico Mecánico 1'),
    ('ODC', 4, 35, 'Almacenista'),
    ('ODC', 4, 36, 'Andamiero 1'),
    ('ODC', 4, 37, 'Auxiliar Ambiental 1'),
    ('ODC', 4, 38, 'Cadenero 1')
),
mapped_roles as (
  select
    t.company_id, t.id as labor_rate_table_id, e.id as labor_rate_entry_id,
    r.client_name, r.level, r.sort_order, r.name
  from official_roles r
  join public.labor_rate_tables t on t.client_name = r.client_name
  join public.labor_rate_entries e on e.labor_rate_table_id = t.id and e.level = r.level
)
insert into public.labor_rate_roles (
  company_id, labor_rate_table_id, labor_rate_entry_id, code, name,
  specialty, specialty_label, summary, receives_hotel, receives_operational_transport, is_active
)
select
  company_id, labor_rate_table_id, labor_rate_entry_id,
  concat(client_name, '-N', level, '-', lpad(sort_order::text, 3, '0')), name,
  'general', 'General', 'Cargo oficial asociado al nivel en el documento fuente.',
  (name ilike '%capataz%' or name ilike '%conductor%'),
  (name ilike '%capataz%' or name ilike '%conductor%'),
  true
from mapped_roles
on conflict (labor_rate_table_id, code) do update set
  labor_rate_entry_id = excluded.labor_rate_entry_id,
  name = excluded.name, specialty = excluded.specialty, specialty_label = excluded.specialty_label,
  summary = excluded.summary, receives_hotel = excluded.receives_hotel,
  receives_operational_transport = excluded.receives_operational_transport, is_active = true, updated_at = now();

-- Source control: expected imported positions: CENIT and ODC according to the documents supplied on 2026-10-08.