-- Índices de claves foráneas consultadas por RLS y trazabilidad.
create index apu_analyses_created_by_idx on public.apu_analyses (created_by);
create index apu_analyses_approved_by_idx on public.apu_analyses (approved_by);
create index apu_versions_company_idx on public.apu_versions (company_id);
create index apu_versions_created_by_idx on public.apu_versions (created_by);
create index apu_versions_approved_by_idx on public.apu_versions (approved_by);
create index apu_version_lines_company_idx on public.apu_version_lines (company_id);
create index apu_version_lines_labor_position_idx on public.apu_version_lines (labor_position_id) where labor_position_id is not null;
create index project_boq_items_company_idx on public.project_boq_items (company_id);
create index project_boq_items_version_idx on public.project_boq_items (apu_version_id);
create index project_boq_cost_entries_company_idx on public.project_boq_cost_entries (company_id);
create index project_boq_cost_entries_created_by_idx on public.project_boq_cost_entries (created_by);

drop policy apu_analyses_manager_write on public.apu_analyses;
drop policy apu_versions_manager_write on public.apu_versions;
drop policy apu_version_lines_manager_write on public.apu_version_lines;
drop policy project_boq_items_manager_write on public.project_boq_items;
drop policy project_boq_cost_entries_manager_write on public.project_boq_cost_entries;

create policy apu_analyses_manager_insert on public.apu_analyses for insert to authenticated with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_analyses.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy apu_analyses_manager_update on public.apu_analyses for update to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_analyses.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management'))) with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_analyses.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy apu_analyses_manager_delete on public.apu_analyses for delete to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_analyses.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));

create policy apu_versions_manager_insert on public.apu_versions for insert to authenticated with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_versions.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy apu_versions_manager_update on public.apu_versions for update to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_versions.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management'))) with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_versions.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy apu_versions_manager_delete on public.apu_versions for delete to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_versions.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));

create policy apu_version_lines_manager_insert on public.apu_version_lines for insert to authenticated with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_version_lines.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy apu_version_lines_manager_update on public.apu_version_lines for update to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_version_lines.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management'))) with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_version_lines.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy apu_version_lines_manager_delete on public.apu_version_lines for delete to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = apu_version_lines.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));

create policy project_boq_items_manager_insert on public.project_boq_items for insert to authenticated with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = project_boq_items.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy project_boq_items_manager_update on public.project_boq_items for update to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = project_boq_items.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management'))) with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = project_boq_items.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy project_boq_items_manager_delete on public.project_boq_items for delete to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = project_boq_items.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));

create policy project_boq_cost_entries_manager_insert on public.project_boq_cost_entries for insert to authenticated with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = project_boq_cost_entries.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy project_boq_cost_entries_manager_update on public.project_boq_cost_entries for update to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = project_boq_cost_entries.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management'))) with check (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = project_boq_cost_entries.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
create policy project_boq_cost_entries_manager_delete on public.project_boq_cost_entries for delete to authenticated using (exists (select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id where ur.user_id = (select auth.uid()) and ur.company_id = project_boq_cost_entries.company_id and r.code in ('administrator', 'resident_engineer', 'inventory_manager', 'general_management')));
