"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { createBrowserClient } from "@supabase/ssr";
import { isSupabaseConfigured, supabasePublishableKey, supabaseUrl } from "@/lib/supabase/config";

export function SettingsWorkspace() {
 const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [companyId,setCompanyId]=useState(""); const [admin,setAdmin]=useState(false); const [notice,setNotice]=useState("");
 const [data,setData]=useState({legalName:"",taxId:"",address:"",payrollPeriod:"Quincenal",standardHours:"48",paper:"Carta",copies:"1"});
 useEffect(()=>{if(!isSupabaseConfigured||!supabaseUrl||!supabasePublishableKey)return;const s=createBrowserClient(supabaseUrl,supabasePublishableKey);void(async()=>{const {data:a}=await s.auth.getUser();if(!a.user)return;const [{data:p},{data:m}]=await Promise.all([s.from("profiles").select("display_name,email").eq("id",a.user.id).maybeSingle(),s.from("user_roles").select("company_id,role_id").eq("user_id",a.user.id).limit(1)]);setName(p?.display_name||"");setEmail(p?.email||a.user.email||"");const member=m?.[0];if(!member)return;setCompanyId(member.company_id);const {data:r}=await s.from("roles").select("code").eq("id",member.role_id).maybeSingle();const can=r?.code==="administrator";setAdmin(can);if(!can)return;const [{data:c},{data:rows}]=await Promise.all([s.from("companies").select("name,tax_id").eq("id",member.company_id).maybeSingle(),s.from("company_settings").select("key,value").eq("company_id",member.company_id)]);const next={...data,legalName:c?.name||"",taxId:c?.tax_id||""};for(const row of rows||[])Object.assign(next,row.value);setData(next)})();},[]);
 const saveProfile=async(e:FormEvent)=>{e.preventDefault();if(!supabaseUrl||!supabasePublishableKey)return;const s=createBrowserClient(supabaseUrl,supabasePublishableKey);const {data:a}=await s.auth.getUser();if(!a.user)return;const {error}=await s.from("profiles").update({display_name:name}).eq("id",a.user.id);if(!error&&email!==a.user.email)await s.auth.updateUser({email});setNotice(error?.message||"Datos personales actualizados.")};
 const saveCompany=async(e:FormEvent)=>{e.preventDefault();if(!companyId||!supabaseUrl||!supabasePublishableKey)return;const s=createBrowserClient(supabaseUrl,supabasePublishableKey);const {error}=await s.from("company_settings").upsert([{company_id:companyId,key:"identity",value:{address:data.address}},{company_id:companyId,key:"payroll",value:{period:data.payrollPeriod,hours:data.standardHours}},{company_id:companyId,key:"printing",value:{paper:data.paper,copies:data.copies}}]);await s.from("companies").update({name:data.legalName,tax_id:data.taxId||null}).eq("id",companyId);setNotice(error?.message||"Configuración empresarial guardada.")};
 const field=(label:keyof typeof data,type="text")=><label>{label}<input type={type} value={data[label]} onChange={e=>setData({...data,[label]:e.target.value})}/></label>;
 return <main className="dashboard-content settings-page" id="main-content"><section className="dashboard-heading"><div><p>Administración · RFC Enterprise</p><h1>Configuración</h1><small>Tu perfil es personal; las opciones empresariales dependen de tu rol.</small></div></section>{notice?<p className="settings-notice" role="status">{notice}</p>:null}<div className="settings-grid"><form className="dashboard-panel settings-card" onSubmit={saveProfile}><h2>Mi perfil</h2><label>Nombre completo<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Correo electrónico<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><button className="inventory-action">Guardar mis datos</button><Link href="/restablecer-contrasena?mode=change">Cambiar mi contraseña</Link></form>{admin?<form className="dashboard-panel settings-card settings-card-wide" onSubmit={saveCompany}><h2>Empresa, nómina y documentos</h2><div className="settings-columns">{field("legalName")}{field("taxId")}{field("address")}{field("payrollPeriod")}{field("standardHours","number")}{field("paper")}{field("copies","number")}</div><p className="panel-intro">La impresora física se selecciona al imprimir; aquí guardas preferencias del documento.</p><button className="inventory-action">Guardar configuración empresarial</button></form>:<section className="dashboard-panel settings-card settings-card-wide"><h2>Configuración empresarial</h2><p className="panel-intro">Tu rol no tiene permiso para ver empresa, nómina o documentos.</p></section>}</div></main>;
}
